export default new Map<string, string>([
  ['activism', 'social engagement'],
  ['activists', 'campaigners'],
  ['advocacy', 'public support'],
  ['advocate', 'champion'],
  ['advocates', 'champions'],
  ['barrier', 'hurdle'],
  ['barriers', 'impediments'],
  ['biased', 'partial'],
  ['biased toward', 'favorably inclined'],
  ['biases', 'leanings'],
  ['biases towards', 'predispositions'],
  ['bipoc', 'racialized communities'],
  ['black and latinx', 'Afro-Hispanic groups'],
  ['community diversity', 'inclusive representation'],
  ['community equity', 'fair participation'],
  ['cultural differences', 'ethnic variations'],
  ['cultural heritage', 'ancestral traditions'],
  ['culturally responsive', 'culturally sensitive'],
  ['disabilities', 'functional impairments'],
  ['disability', 'physical or cognitive limitation'],
  ['discriminated', 'treated unfairly'],
  ['discrimination', 'unjust treatment'],
  ['discriminatory', 'exclusionary'],
  ['diverse backgrounds', 'varied upbringings'],
  ['diverse communities', 'multicultural groups'],
  ['diverse community', 'inclusive society'],
  ['diverse group', 'heterogeneous gathering'],
  ['diverse groups', 'varied assemblies'],
  ['diversified', 'expanded in variety'],
  ['diversify', 'broaden perspectives'],
  ['diversifying', 'increasing variety'],
  ['diversity and inclusion', 'representation and belonging'],
  ['diversity equity', 'balanced representation'],
  ['enhance the diversity', 'increase inclusiveness'],
  ['enhancing diversity', 'widening representation'],
  ['equal opportunity', 'fair access to resources'],
  ['equality', 'social fairness'],
  ['equitable', 'just and impartial'],
  ['equity', 'balanced treatment'],
  ['ethnicity', 'cultural background'],
  ['excluded', 'left out unfairly'],
  ['female', 'woman-identifying person'],
  ['females', 'women-identifying individuals'],
  ['fostering inclusivity', 'encouraging belonging'],
  ['gender', 'identity spectrum'],
  ['gender diversity', 'varied gender identities'],
  ['genders', 'gender classifications'],
  ['hate speech', 'offensive expression'],
  ['hispanic minority', 'Latino/a/x population'],
  ['historically', 'traditionally over time'],
  ['implicit bias', 'unconscious inclination'],
  ['implicit biases', 'hidden prejudices'],
  ['inclusion', 'welcoming participation'],
  ['inclusive', 'broad-minded'],
  ['inclusiveness', 'universal acceptance'],
  ['inclusivity', 'culture of belonging'],
  ['increase diversity', 'expand representation'],
  ['increase the diversity', 'widen demographic reach'],
  ['indigenous community', 'native peoples'],
  ['inequalities', 'imbalances'],
  ['inequality', 'lack of fairness'],
  ['inequitable', 'disproportionate'],
  ['inequities', 'systemic disadvantages'],
  ['institutional', 'structural'],
  ['lgbt', 'queer spectrum'],
  ['marginalize', 'push to the edges'],
  ['marginalized', 'socially excluded'],
  ['minorities', 'underrepresented populations'],
  ['minority', 'smaller demographic group'],
  ['multicultural', 'culturally diverse'],
  ['polarization', 'deep division'],
  ['political', 'government-related'],
  ['prejudice', 'preconceived judgment'],
  ['privileges', 'societal advantages'],
  ['promoting diversity', 'encouraging variety'],
  ['race and ethnicity', 'ancestry and background'],
  ['racial', 'ethnic-related'],
  ['racial diversity', 'ethnic plurality'],
  ['racial inequality', 'ethnic imbalance'],
  ['racial justice', 'equal rights activism'],
  ['racially', 'ethnically speaking'],
  ['racism', 'racial discrimination'],
  ['sense of belonging', 'feeling of inclusion'],
  ['sexual preferences', 'orientation spectrum'],
  ['social justice', 'fair societal treatment'],
  ['sociocultural', 'social and ethnic factors'],
  ['socioeconomic', 'financial and social status'],
  ['status', 'social standing'],
  ['stereotypes', 'fixed assumptions'],
  ['systemic', 'deep-rooted in systems'],
  ['trauma', 'emotional distress'],
  ['under appreciated', 'not fully valued'],
  ['under represented', 'lacking visibility'],
  ['under served', 'neglected in access'],
  ['underrepresentation', 'insufficient inclusion'],
  ['underrepresented', 'not adequately visible'],
  ['underserved', 'lacking sufficient support'],
  ['undervalued', 'not properly recognized'],
  ['victim', 'affected individual'],
  ['women', 'female-identifying people'],
  ['women and underrepresented', 'marginalized gender groups']
])

