export default new Map<string, string>([
  ['activism', 'social engagement'],
  ['activists', 'campaigners'],
  ['advocacy', 'public support'],
  ['advocate', 'champion'],
  ['advocates', 'champions'],
  ['barrier', 'hurdle'],
  ['barriers', 'impediments'],
  ['biased', 'partial'],
  ['biased toward', 'favorably inclined'],
  ['biases', 'leanings'],
  ['biases towards', 'predispositions'],
  ['bipoc', 'black or indigenous'],
  ['black and latinx', 'black and latino'],
  ['community diversity', 'community social variance'],
  ['community equity', 'fair participation'],
  ['cultural differences', 'ethnic variations'],
  ['cultural heritage', 'ancestral traditions'],
  ['culturally responsive', 'culturally sensitive'],
  ['disabilities', 'functional impairments'],
  ['disability', 'physical or cognitive limitation'],
  ['discriminated', 'treated unfairly'],
  ['discrimination', 'unjust treatment'],
  ['discriminatory', 'exclusionary'],
  ['diverse backgrounds', 'varied upbringings'],
  ['diverse communities', 'communities of varying backgrounds'],
  ['diverse community', 'varied community'],
  ['diverse group', 'heterogeneous gathering'],
  ['diverse groups', 'varied assemblies'],
  ['diversified', 'expanded in variety'],
  ['diversify', 'broaden perspectives'],
  ['diversifying', 'increasing variety'],
  ['diversity and inclusion', 'fair social representation'],
  ['diversity equity', 'balanced representation'],
  ['enhance the diversity', 'increase the cultural breadth'],
  ['enhancing diversity', 'increasing the cultural breadth'],
  ['equal opportunity', 'fair access to resources'],
  ['equality', 'social fairness'],
  ['equitable', 'just and impartial'],
  ['equity', 'balanced treatment'],
  ['ethnicity', 'cultural background'],
  ['excluded', 'left out unfairly'],
  ['female', 'non-male'],
  ['females', 'non-males'],
  ['fostering inclusivity', 'encouraging belonging'],
  ['gender', 'identity spectrum'],
  ['gender diversity', 'breadth of sexual identities'],
  ['genders', 'sexes'],
  ['hate speech', 'offensive expression'],
  ['hispanic minority', 'Latino/a/x population'],
  ['historically', 'traditionally over time'],
  ['implicit bias', 'unconscious inclination'],
  ['implicit biases', 'unconscious inclinations'],
  ['inclusion', 'welcoming participation'],
  ['inclusive', 'broad-minded'],
  ['inclusiveness', 'universal acceptance'],
  ['inclusivity', 'culture of belonging'],
  ['increase diversity', 'expand representation'],
  ['increase the diversity', 'widen demographic reach'],
  ['indigenous community', 'native peoples'],
  ['inequalities', 'imbalances'],
  ['inequality', 'lack of fairness'],
  ['inequitable', 'disproportionate'],
  ['inequities', 'imbalances'],
  ['institutional', 'structural'],
  ['lgbt', 'queer spectrum'],
  ['marginalize', 'unfairly disregard'],
  ['marginalized', 'unfairly disregarded'],
  ['minorities', 'non-majority demographic groups'],
  ['minority', 'smaller demographic group'],
  ['multicultural', 'culturally diverse'],
  ['polarization', 'deep division'],
  ['political', 'government-related'],
  ['prejudice', 'preconceived judgment'],
  ['privileges', 'societal advantages'],
  ['promoting diversity', 'encouraging variety'],
  ['race and ethnicity', 'ancestry and background'],
  ['racial', 'ethnic-related'],
  ['racial diversity', 'ethnic plurality'],
  ['racial inequality', 'ethnic imbalance'],
  ['racial justice', 'ethnic justice'],
  ['racially', 'ethnically'],
  ['racism', 'ethnic bigotry'],
  ['sense of belonging', 'sense of community'],
  ['sexual preferences', 'orientation spectrum'],
  ['social justice', 'fair societal treatment'],
  ['sociocultural', 'social and cultural'],
  ['socioeconomic', 'social and economic'],
  ['status', 'social standing'],
  ['stereotypes', 'fixed assumptions'],
  ['systemic', 'deep-rooted'],
  ['trauma', 'emotional distress'],
  ['under appreciated', 'not fully valued'],
  ['under represented', 'lacking visibility'],
  ['under served', 'neglected in access'],
  ['underrepresentation', 'insufficient representation'],
  ['underrepresented', 'not adequately included'],
  ['underserved', 'lacking sufficient support'],
  ['undervalued', 'not properly recognized'],
  ['victim', 'affected individual'],
  ['women', 'ladies'],
  ['women and underrepresented', 'ladies and lesser-served social groups']
])

