export default new Map<string, string>([
	['activism', 'social movement'],
	['activists', 'change agents'],
	['advocacy', 'active support'],
	['advocate', 'proponent'],
	['advocates', 'proponents'],
	['barrier', 'obstacle'],
	['barriers', 'obstacles'],
	['biased', 'lacking impartiality'],
	['biased toward', 'predisposed to favor'],
	['biases', 'leanings'],
	['biases towards', 'prejudicial leanings'],
	['bipoc', 'people of color'],
	['black and latinx', 'people of African and Latin origin'],
	['community diversity', 'varied demographic mix'],
	['community equity', 'fair distribution among populations'],
	['cultural differences', 'societal contrasts'],
	['cultural heritage', 'ancestral legacy'],
	['culturally responsive', 'contextually adaptive'],
	['disabilities disability', 'functional impairments'],
	['discriminated', 'mistreated'],
	['discrimination', 'unfair treatment'],
	['discriminatory', 'exclusionary'],
	['diverse backgrounds', 'varied origins'],
	['diverse communities', 'mixed populations'],
	['diverse community', 'heterogeneous collective'],
	['diverse group', 'varied assembly'],
	['diverse groups', 'varied collectives'],
	['diversified', 'expanded range'],
	['diversify', 'broaden composition'],
	['diversifying', 'broadening composition'],
	['diversity and inclusion', 'varied representation with integration'],
	['diversity', 'variety'],
	['equity', 'fairness'],
	['enhance the diversity', 'broaden representation'],
	['enhancing diversity', 'expanding variety'],
	['equal opportunity', 'fair access'],
	['equality', 'parity'],
	['equitable', 'impartial'],
	['ethnicity', 'ancestry'],
	['excluded', 'omitted'],
	['female', 'woman'],
	['females', 'ladies'],
	['fostering inclusivity', 'nurturing integration'],
	['gender', 'sex'],
	['gender diversity', 'varied sex composition'],
	['genders', 'sexes'],
	['hate speech', 'derogatory remarks'],
	['hate', 'loathing'],
	['speech', 'oration'],
	['hispanic', 'latino'],
	['minority', 'smaller segment'],
	['historically', 'traditionally'],
	['implicit bias', 'unconscious partiality'],
	['implicit biases', 'unconscious leanings'],
	['inclusion', 'integration'],
	['inclusive', 'embracing all'],
	['inclusiveness', 'comprehensive acceptance'],
	['inclusivity', 'integrative quality'],
	['increase diversity', 'boost variety'],
	['increase the diversity', 'expand range'],
	['indigenous community', 'native population'],
	['inequalities', 'disparities'],
	['inequality', 'imbalance'],
	['inequitable', 'unjust'],
	['inequities', 'injustices'],
	['institutional', 'organizational'],
	['lgbt', 'queer individuals'],
	['marginalize', 'sideline'],
	['marginalized', 'sidelined'],
	['minorities', 'smaller groups'],
	['multicultural', 'cross-cultural'],
	['polarization', 'division'],
	['political', 'governmental'],
	['prejudice', 'preconception'],
	['privileges', 'advantages'],
	['promoting', 'advancing'],
	['race and ethnicity', 'ancestry and background'],
	['racial', 'color-based'],
	['racial diversity', 'varied color representation'],
	['racial inequality', 'color imbalance'],
	['racial justice', 'color fairness'],
	['racially', 'in a color-based manner'],
	['racism', 'ethnocentrism'],
	['sense of belonging', 'feeling of connectedness'],
	['sexual preferences', 'intimate inclinations'],
	['social justice', 'communal fairness'],
	['socio cultural', 'socially-informed'],
	['socio economic', 'financially based'],
	['sociocultural', 'social customs'],
	['socioeconomic status', 'financial standing'],
	['stereotypes', 'generalizations'],
	['systemic', 'structural'],
	['trauma', 'psychological injury'],
	['under appreciated', 'insufficiently recognized'],
	['under represented', 'insufficiently visible'],
	['under served', 'poorly supported'],
	['underrepresentation', 'lack of visibility'],
	['underrepresented', 'minimally visible'],
	['underserved', 'poorly resourced'],
	['undervalued', 'underrated'],
	['victim', 'sufferer'],
	['women', 'feminine adults'],
	['women and underrepresented', 'feminine individuals and less visible groups'],
	['antiracist', 'anti-oppression'],
	['community', 'collective'],
	['disabilities', 'impairments'],
	['disability', 'impairment']
]);
